[build]
  publish = "AIDIFY NEW START V1"
  command = ""

[[redirects]]
  from = "/api/*"
  to = "https://aidify-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://aidify-backend.onrender.com/uploads/:splat"
  status = 200
  force = true
